### ISSUE TITLE
Missing orgs.list_saml_sso_authorizations and other enterprise endpoints

### ISSUE THREAD

**Issue by rupaschomaker** [fastai/ghapi#167]
On the last api update, a bunch of enterprise endpoints were removed.  I noticed that the github documentation is now split between the regular versions of github and the enterprise cloud version of github:

https://docs.github.com/en/enterprise-cloud@latest/rest/orgs/orgs?apiVersion=2022-11-28#list-saml-sso-authorizations-for-an-organization

whereas regular github doesn't have this endpoint documented:
https://docs.github.com/en/rest/orgs/orgs?apiVersion=2022-11-28

This is of course breaking any any calls that depended on the enterprise endpoints.

**Comment by rupaschomaker** [comment]
A refresh of this would also pickup the github copilot endpoints...

**Comment by tyleris-irish** [comment]
Any update on this? Its a shame that I have to manually link the API calls and cannot rely on the simple method.

The following code gives an error,  
  
![Image](https://github.com/user-attachments/assets/c0eb132a-ab10-4e83-88ac-76bd15a5e9ea)

```BASH
Traceback (most recent call last):
  File "/home/ty669118/gitfiles/enterprise-billing/hello.py", line 23, in <module>
    main()
    ~~~~^^
  File "/home/ty669118/gitfiles/enterprise-billing/hello.py", line 11, in main
    print(api.billing.get_github_actions_billing_ghe(enterprise='ucf'))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: '_GhVerbGroup' object has no attribute 'get_github_actions_billing_ghe'. Did you mean: 'get_github_actions_billing_org'?
```

ucf is the correct slug for the enterprise
